version: "3.9"

networks:
  futurespace:


services:
  mysql-futurespace:
    image: mysql
    container_name: mysql-futurespace
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: 'future_space'
    networks:
      - futurespace

  app-futurespace:
    build:
      context: ./FutureSpace/
      dockerfile: Dockerfile
      args:
        version: 1
    image: app-futurespace
    container_name: app-futurespace
    restart: always
    ports:
      - 80:80
    networks:
      - futurespace
    environment:
      - MYSQL_HOST=mysql-futurespace
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=future_space
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysql-futurespace
