version: "3.9"

networks:
  futurespace:


services:
  mysql-futurespace:
    image: mysql
    container_name: mysql-futurespace
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: 'future_space'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    expose:
      - 3310
    networks:
      - futurespace

  app-futurespace:
    build:
      context: ./FutureSpace/
      dockerfile: Dockerfile
      args:
        version: 1
    image: app-futurespace
    container_name: app-futurespace
    networks:
      - futurespace
    environment:
      - MYSQL_HOST=mysql-futurespace
      - MYSQL_PORT=3310
      - MYSQL_DATABASE=future_space
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysql-futurespace
